version: '3'

services:
  foreman:
    image: ${IMAGE_PREFIX}/foreman:${IMAGE_TAG}
    container_name: foreman
    hostname: ${FOREMAN_HOSTNAME}.${DOMAIN}
    environment:  
      FOREMAN_WEB_CA: ${FOREMAN_WEB_CA:-""}
      FOREMAN_WEB_PUBLIC_CERT: ${FOREMAN_WEB_PUBLIC_CERT:-""}
      FOREMAN_WEB_PRIVATE_CERT: ${FOREMAN_WEB_PRIVATE_CERT:-""}
      RESET_ADMIN_PASSWORD: ${RESET_ADMIN_PASSWORD:-""}
      PGPASSWORD: postgres
      PGUSER: postgres
      FOREMAN_OPTS:
        --puppet-server=false
        --puppet-agent=false
        --foreman-proxy-puppet=false
        --foreman-proxy-puppetca=false
        --foreman-proxy-tftp=false
        --foreman-proxy-realm=false
        --foreman-proxy-dns=false
        --foreman-proxy-dhcp=false
        --foreman-proxy-bmc=false
        --puppet-puppetmaster=puppet
        --foreman-db-type=postgresql
        --foreman-db-manage=false
        --foreman-db-manage-rake=false
        --foreman-db-username=foreman
        --foreman-db-password=foreman
        --foreman-db-host=postgres
        --foreman-db-database=foreman
        --foreman-proxy-puppet-url=https://${PUPPET_HOSTNAME}.${DOMAIN}
        --foreman-proxy-trusted-hosts=https://${PUPPET_HOSTNAME}.${DOMAIN}
        --foreman-proxy-trusted-hosts=https://${PUPPET_HOSTNAME}
      #IGNORED_ENVIRONMENTS_FILTERS: ${IGNORED_ENVIRONMENTS_FILTERS}
      #IGNORED_ENVIRONMENTS_IGNORED: ${IGNORED_ENVIRONMENTS_IGNORED}
      IMPORT_ONLY_ROLES_AND_PROFILES: $IMPORT_ONLY_ROLES_AND_PROFILES
    build:
      context: ./foreman
      args:
        FOREMAN_VERSION: $FOREMAN_VERSION
    depends_on:
      - postgres
    volumes:
      - ./volumes/puppet/ssl:/etc/puppetlabs/puppet/ssl/
      - ./volumes/foreman/accounts:/tmp/accounts
    ports:
      - 443:443
  puppet:
    container_name: puppet
    hostname: ${PUPPET_HOSTNAME}
    build: 
      context: ./puppet
      args:
        FOREMAN_VERSION: $FOREMAN_VERSION
    image: ${IMAGE_PREFIX}/puppet:${IMAGE_TAG}
    ports:
      - 8140:8140
      - 8443:8443
    volumes:
      - ./volumes/puppet/ssl:/etc/puppetlabs/puppet/ssl/
      - ./volumes/puppet/code:/etc/puppetlabs/code
    depends_on:
      - foreman
    links:
      - foreman:${FOREMAN_HOSTNAME}
      - foreman:${FOREMAN_HOSTNAME}.${DOMAIN}
    environment:
      # MAX_ACTIVE_INSTANCES: $MAX_ACTIVE_INSTANCES
      PUPPETDB_SERVER_URLS: https://${PUPPETDB_HOSTNAME}.${DOMAIN}:8081
      FOREMAN_HOSTNAME: ${FOREMAN_HOSTNAME}
      PUPPET_HOSTNAME: ${PUPPET_HOSTNAME}
      DOMAIN: ${DOMAIN}
      AUTOSIGN: ${AUTOSIGN}
      PUPPETSERVER_JAVA_ARGS: ${PUPPETSERVER_JAVA_ARGS:-"-Xms128m -Xmx128m"}
      FOREMAN_WEB_CA: ${FOREMAN_WEB_CA:-""}
  postgres:
    container_name: postgres
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      COMPOSE_PROJECT_NAME: postgres
    ports:
      - 5432
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
      - ./volumes/postgres/scripts:/docker-entrypoint-initdb.d
  r10k:
    container_name: r10k
    environment:
      R10K_REPO: ${R10K_REPO}
    build:
      context: ./r10k
    image: ${IMAGE_PREFIX}/r10k:${IMAGE_TAG}
    ports:
      - 8088:8088
    volumes:
      - ./volumes/puppet/code:/etc/puppetlabs/code
  puppetdb:
    container_name: puppetdb
    hostname: ${PUPPETDB_HOSTNAME}.${DOMAIN}
    depends_on:
      - postgres
      - puppet
    links:
      - puppet:puppet
      - postgres:postgres
    image: puppet/puppetdb
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ./volumes/puppet/ssl:/etc/puppetlabs/puppet/ssl/
  post_config:
    image: python:3
    container_name: post_config
    working_dir: /usr/local/app
    command: ["/bin/bash", "./wrapper.sh"]
    environment:
      PUPPET_HOSTNAME: ${PUPPET_HOSTNAME}
      FOREMAN_HOSTNAME: ${FOREMAN_HOSTNAME}
      DOMAIN: ${DOMAIN}
    volumes:
      - ./volumes/post_scripts:/usr/local/app
      - ./volumes/foreman/accounts:/tmp/accounts
